services:
  api:
    build: ./services/api
    depends_on:
      - weaviate
      - opensearch
    environment:
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - EVAL_DB_PATH=/data/evaluations.sqlite
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp.json
      - GCP_PROJECT=${GCP_PROJECT}
      - GCP_LOCATION=${GCP_LOCATION}
      - GEMINI_MODEL=${GEMINI_MODEL}
    ports:
      - "8000:8000"
    volumes:
      - eval_data:/data
      - ./secrets:/secrets:ro

  weaviate:
    image: semitechnologies/weaviate:1.32.7
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-google"
      ENABLE_MODULES: "text2vec-google,generative-google"
      GRPC_PORT: "50051"
      GOOGLE_PROJECT_ID: ${GCP_PROJECT}
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp.json
      CLUSTER_HOSTNAME: "node1"
      USE_GOOGLE_AUTH: "true"
    volumes:
      - weaviate_data:/var/lib/weaviate
      - ./secrets:/secrets:ro
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - cluster.name=opensearch
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      # If you switch to 3.x and enable security, set OPENSEARCH_INITIAL_ADMIN_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

volumes:
  weaviate_data:
  opensearch_data:
  eval_data:
